<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Rdsmysqlv2\Model;

use ArrayAccess;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\ModelInterface;

class ModifyDBNodeTemporarySpecRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ModifyDBNodeTemporarySpecRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'estimate_only' => 'bool',
        'instance_id' => 'string',
        'node_info' => '\Volcengine\Rdsmysqlv2\Model\NodeInfoForModifyDBNodeTemporarySpecInput[]',
        'request_source' => 'string',
        'rollback_time' => 'string',
        'specified_switch_end_time' => 'string',
        'specified_switch_start_time' => 'string',
        'switch_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'estimate_only' => null,
        'instance_id' => null,
        'node_info' => null,
        'request_source' => null,
        'rollback_time' => null,
        'specified_switch_end_time' => null,
        'specified_switch_start_time' => null,
        'switch_type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'estimate_only' => 'EstimateOnly',
        'instance_id' => 'InstanceId',
        'node_info' => 'NodeInfo',
        'request_source' => 'RequestSource',
        'rollback_time' => 'RollbackTime',
        'specified_switch_end_time' => 'SpecifiedSwitchEndTime',
        'specified_switch_start_time' => 'SpecifiedSwitchStartTime',
        'switch_type' => 'SwitchType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'estimate_only' => 'setEstimateOnly',
        'instance_id' => 'setInstanceId',
        'node_info' => 'setNodeInfo',
        'request_source' => 'setRequestSource',
        'rollback_time' => 'setRollbackTime',
        'specified_switch_end_time' => 'setSpecifiedSwitchEndTime',
        'specified_switch_start_time' => 'setSpecifiedSwitchStartTime',
        'switch_type' => 'setSwitchType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'estimate_only' => 'getEstimateOnly',
        'instance_id' => 'getInstanceId',
        'node_info' => 'getNodeInfo',
        'request_source' => 'getRequestSource',
        'rollback_time' => 'getRollbackTime',
        'specified_switch_end_time' => 'getSpecifiedSwitchEndTime',
        'specified_switch_start_time' => 'getSpecifiedSwitchStartTime',
        'switch_type' => 'getSwitchType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['estimate_only'] = isset($data['estimate_only']) ? $data['estimate_only'] : null;
        $this->container['instance_id'] = isset($data['instance_id']) ? $data['instance_id'] : null;
        $this->container['node_info'] = isset($data['node_info']) ? $data['node_info'] : null;
        $this->container['request_source'] = isset($data['request_source']) ? $data['request_source'] : null;
        $this->container['rollback_time'] = isset($data['rollback_time']) ? $data['rollback_time'] : null;
        $this->container['specified_switch_end_time'] = isset($data['specified_switch_end_time']) ? $data['specified_switch_end_time'] : null;
        $this->container['specified_switch_start_time'] = isset($data['specified_switch_start_time']) ? $data['specified_switch_start_time'] : null;
        $this->container['switch_type'] = isset($data['switch_type']) ? $data['switch_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['instance_id'] === null) {
            $invalidProperties[] = "'instance_id' can't be null";
        }
        if ($this->container['rollback_time'] === null) {
            $invalidProperties[] = "'rollback_time' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets estimate_only
     *
     * @return bool
     */
    public function getEstimateOnly()
    {
        return $this->container['estimate_only'];
    }

    /**
     * Sets estimate_only
     *
     * @param bool $estimate_only estimate_only
     *
     * @return $this
     */
    public function setEstimateOnly($estimate_only)
    {
        $this->container['estimate_only'] = $estimate_only;

        return $this;
    }

    /**
     * Gets instance_id
     *
     * @return string
     */
    public function getInstanceId()
    {
        return $this->container['instance_id'];
    }

    /**
     * Sets instance_id
     *
     * @param string $instance_id instance_id
     *
     * @return $this
     */
    public function setInstanceId($instance_id)
    {
        $this->container['instance_id'] = $instance_id;

        return $this;
    }

    /**
     * Gets node_info
     *
     * @return \Volcengine\Rdsmysqlv2\Model\NodeInfoForModifyDBNodeTemporarySpecInput[]
     */
    public function getNodeInfo()
    {
        return $this->container['node_info'];
    }

    /**
     * Sets node_info
     *
     * @param \Volcengine\Rdsmysqlv2\Model\NodeInfoForModifyDBNodeTemporarySpecInput[] $node_info node_info
     *
     * @return $this
     */
    public function setNodeInfo($node_info)
    {
        $this->container['node_info'] = $node_info;

        return $this;
    }

    /**
     * Gets request_source
     *
     * @return string
     */
    public function getRequestSource()
    {
        return $this->container['request_source'];
    }

    /**
     * Sets request_source
     *
     * @param string $request_source request_source
     *
     * @return $this
     */
    public function setRequestSource($request_source)
    {
        $this->container['request_source'] = $request_source;

        return $this;
    }

    /**
     * Gets rollback_time
     *
     * @return string
     */
    public function getRollbackTime()
    {
        return $this->container['rollback_time'];
    }

    /**
     * Sets rollback_time
     *
     * @param string $rollback_time rollback_time
     *
     * @return $this
     */
    public function setRollbackTime($rollback_time)
    {
        $this->container['rollback_time'] = $rollback_time;

        return $this;
    }

    /**
     * Gets specified_switch_end_time
     *
     * @return string
     */
    public function getSpecifiedSwitchEndTime()
    {
        return $this->container['specified_switch_end_time'];
    }

    /**
     * Sets specified_switch_end_time
     *
     * @param string $specified_switch_end_time specified_switch_end_time
     *
     * @return $this
     */
    public function setSpecifiedSwitchEndTime($specified_switch_end_time)
    {
        $this->container['specified_switch_end_time'] = $specified_switch_end_time;

        return $this;
    }

    /**
     * Gets specified_switch_start_time
     *
     * @return string
     */
    public function getSpecifiedSwitchStartTime()
    {
        return $this->container['specified_switch_start_time'];
    }

    /**
     * Sets specified_switch_start_time
     *
     * @param string $specified_switch_start_time specified_switch_start_time
     *
     * @return $this
     */
    public function setSpecifiedSwitchStartTime($specified_switch_start_time)
    {
        $this->container['specified_switch_start_time'] = $specified_switch_start_time;

        return $this;
    }

    /**
     * Gets switch_type
     *
     * @return string
     */
    public function getSwitchType()
    {
        return $this->container['switch_type'];
    }

    /**
     * Sets switch_type
     *
     * @param string $switch_type switch_type
     *
     * @return $this
     */
    public function setSwitchType($switch_type)
    {
        $this->container['switch_type'] = $switch_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

