<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Partner\Model;

use ArrayAccess;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\ModelInterface;

class ListChildPartnerCustomerRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ListChildPartnerCustomerRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'child_partner_name' => 'string',
        'child_partner_passport_id' => 'string',
        'customer_passport_id' => 'string',
        'limit' => 'int',
        'offset' => 'int',
        'precise_customer_names' => 'string[]',
        'relate_end_time' => 'string',
        'relate_start_time' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'child_partner_name' => null,
        'child_partner_passport_id' => null,
        'customer_passport_id' => null,
        'limit' => 'int64',
        'offset' => 'int64',
        'precise_customer_names' => null,
        'relate_end_time' => null,
        'relate_start_time' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'child_partner_name' => 'ChildPartnerName',
        'child_partner_passport_id' => 'ChildPartnerPassportID',
        'customer_passport_id' => 'CustomerPassportID',
        'limit' => 'Limit',
        'offset' => 'Offset',
        'precise_customer_names' => 'PreciseCustomerNames',
        'relate_end_time' => 'RelateEndTime',
        'relate_start_time' => 'RelateStartTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'child_partner_name' => 'setChildPartnerName',
        'child_partner_passport_id' => 'setChildPartnerPassportId',
        'customer_passport_id' => 'setCustomerPassportId',
        'limit' => 'setLimit',
        'offset' => 'setOffset',
        'precise_customer_names' => 'setPreciseCustomerNames',
        'relate_end_time' => 'setRelateEndTime',
        'relate_start_time' => 'setRelateStartTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'child_partner_name' => 'getChildPartnerName',
        'child_partner_passport_id' => 'getChildPartnerPassportId',
        'customer_passport_id' => 'getCustomerPassportId',
        'limit' => 'getLimit',
        'offset' => 'getOffset',
        'precise_customer_names' => 'getPreciseCustomerNames',
        'relate_end_time' => 'getRelateEndTime',
        'relate_start_time' => 'getRelateStartTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['child_partner_name'] = isset($data['child_partner_name']) ? $data['child_partner_name'] : null;
        $this->container['child_partner_passport_id'] = isset($data['child_partner_passport_id']) ? $data['child_partner_passport_id'] : null;
        $this->container['customer_passport_id'] = isset($data['customer_passport_id']) ? $data['customer_passport_id'] : null;
        $this->container['limit'] = isset($data['limit']) ? $data['limit'] : null;
        $this->container['offset'] = isset($data['offset']) ? $data['offset'] : null;
        $this->container['precise_customer_names'] = isset($data['precise_customer_names']) ? $data['precise_customer_names'] : null;
        $this->container['relate_end_time'] = isset($data['relate_end_time']) ? $data['relate_end_time'] : null;
        $this->container['relate_start_time'] = isset($data['relate_start_time']) ? $data['relate_start_time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['limit'] === null) {
            $invalidProperties[] = "'limit' can't be null";
        }
        if ($this->container['offset'] === null) {
            $invalidProperties[] = "'offset' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets child_partner_name
     *
     * @return string
     */
    public function getChildPartnerName()
    {
        return $this->container['child_partner_name'];
    }

    /**
     * Sets child_partner_name
     *
     * @param string $child_partner_name child_partner_name
     *
     * @return $this
     */
    public function setChildPartnerName($child_partner_name)
    {
        $this->container['child_partner_name'] = $child_partner_name;

        return $this;
    }

    /**
     * Gets child_partner_passport_id
     *
     * @return string
     */
    public function getChildPartnerPassportId()
    {
        return $this->container['child_partner_passport_id'];
    }

    /**
     * Sets child_partner_passport_id
     *
     * @param string $child_partner_passport_id child_partner_passport_id
     *
     * @return $this
     */
    public function setChildPartnerPassportId($child_partner_passport_id)
    {
        $this->container['child_partner_passport_id'] = $child_partner_passport_id;

        return $this;
    }

    /**
     * Gets customer_passport_id
     *
     * @return string
     */
    public function getCustomerPassportId()
    {
        return $this->container['customer_passport_id'];
    }

    /**
     * Sets customer_passport_id
     *
     * @param string $customer_passport_id customer_passport_id
     *
     * @return $this
     */
    public function setCustomerPassportId($customer_passport_id)
    {
        $this->container['customer_passport_id'] = $customer_passport_id;

        return $this;
    }

    /**
     * Gets limit
     *
     * @return int
     */
    public function getLimit()
    {
        return $this->container['limit'];
    }

    /**
     * Sets limit
     *
     * @param int $limit limit
     *
     * @return $this
     */
    public function setLimit($limit)
    {
        $this->container['limit'] = $limit;

        return $this;
    }

    /**
     * Gets offset
     *
     * @return int
     */
    public function getOffset()
    {
        return $this->container['offset'];
    }

    /**
     * Sets offset
     *
     * @param int $offset offset
     *
     * @return $this
     */
    public function setOffset($offset)
    {
        $this->container['offset'] = $offset;

        return $this;
    }

    /**
     * Gets precise_customer_names
     *
     * @return string[]
     */
    public function getPreciseCustomerNames()
    {
        return $this->container['precise_customer_names'];
    }

    /**
     * Sets precise_customer_names
     *
     * @param string[] $precise_customer_names precise_customer_names
     *
     * @return $this
     */
    public function setPreciseCustomerNames($precise_customer_names)
    {
        $this->container['precise_customer_names'] = $precise_customer_names;

        return $this;
    }

    /**
     * Gets relate_end_time
     *
     * @return string
     */
    public function getRelateEndTime()
    {
        return $this->container['relate_end_time'];
    }

    /**
     * Sets relate_end_time
     *
     * @param string $relate_end_time relate_end_time
     *
     * @return $this
     */
    public function setRelateEndTime($relate_end_time)
    {
        $this->container['relate_end_time'] = $relate_end_time;

        return $this;
    }

    /**
     * Gets relate_start_time
     *
     * @return string
     */
    public function getRelateStartTime()
    {
        return $this->container['relate_start_time'];
    }

    /**
     * Sets relate_start_time
     *
     * @param string $relate_start_time relate_start_time
     *
     * @return $this
     */
    public function setRelateStartTime($relate_start_time)
    {
        $this->container['relate_start_time'] = $relate_start_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

