<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Natgateway\Model;

use ArrayAccess;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\ModelInterface;

class SnatEntryForDescribeSnatEntriesOutput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SnatEntryForDescribeSnatEntriesOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'eip_address' => 'string',
        'eip_id' => 'string',
        'nat_gateway_id' => 'string',
        'nat_ip_id' => 'string',
        'snat_entry_id' => 'string',
        'snat_entry_name' => 'string',
        'source_cidr' => 'string',
        'status' => 'string',
        'subnet_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'eip_address' => null,
        'eip_id' => null,
        'nat_gateway_id' => null,
        'nat_ip_id' => null,
        'snat_entry_id' => null,
        'snat_entry_name' => null,
        'source_cidr' => null,
        'status' => null,
        'subnet_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'eip_address' => 'EipAddress',
        'eip_id' => 'EipId',
        'nat_gateway_id' => 'NatGatewayId',
        'nat_ip_id' => 'NatIpId',
        'snat_entry_id' => 'SnatEntryId',
        'snat_entry_name' => 'SnatEntryName',
        'source_cidr' => 'SourceCidr',
        'status' => 'Status',
        'subnet_id' => 'SubnetId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'eip_address' => 'setEipAddress',
        'eip_id' => 'setEipId',
        'nat_gateway_id' => 'setNatGatewayId',
        'nat_ip_id' => 'setNatIpId',
        'snat_entry_id' => 'setSnatEntryId',
        'snat_entry_name' => 'setSnatEntryName',
        'source_cidr' => 'setSourceCidr',
        'status' => 'setStatus',
        'subnet_id' => 'setSubnetId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'eip_address' => 'getEipAddress',
        'eip_id' => 'getEipId',
        'nat_gateway_id' => 'getNatGatewayId',
        'nat_ip_id' => 'getNatIpId',
        'snat_entry_id' => 'getSnatEntryId',
        'snat_entry_name' => 'getSnatEntryName',
        'source_cidr' => 'getSourceCidr',
        'status' => 'getStatus',
        'subnet_id' => 'getSubnetId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['eip_address'] = isset($data['eip_address']) ? $data['eip_address'] : null;
        $this->container['eip_id'] = isset($data['eip_id']) ? $data['eip_id'] : null;
        $this->container['nat_gateway_id'] = isset($data['nat_gateway_id']) ? $data['nat_gateway_id'] : null;
        $this->container['nat_ip_id'] = isset($data['nat_ip_id']) ? $data['nat_ip_id'] : null;
        $this->container['snat_entry_id'] = isset($data['snat_entry_id']) ? $data['snat_entry_id'] : null;
        $this->container['snat_entry_name'] = isset($data['snat_entry_name']) ? $data['snat_entry_name'] : null;
        $this->container['source_cidr'] = isset($data['source_cidr']) ? $data['source_cidr'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['subnet_id'] = isset($data['subnet_id']) ? $data['subnet_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets eip_address
     *
     * @return string
     */
    public function getEipAddress()
    {
        return $this->container['eip_address'];
    }

    /**
     * Sets eip_address
     *
     * @param string $eip_address eip_address
     *
     * @return $this
     */
    public function setEipAddress($eip_address)
    {
        $this->container['eip_address'] = $eip_address;

        return $this;
    }

    /**
     * Gets eip_id
     *
     * @return string
     */
    public function getEipId()
    {
        return $this->container['eip_id'];
    }

    /**
     * Sets eip_id
     *
     * @param string $eip_id eip_id
     *
     * @return $this
     */
    public function setEipId($eip_id)
    {
        $this->container['eip_id'] = $eip_id;

        return $this;
    }

    /**
     * Gets nat_gateway_id
     *
     * @return string
     */
    public function getNatGatewayId()
    {
        return $this->container['nat_gateway_id'];
    }

    /**
     * Sets nat_gateway_id
     *
     * @param string $nat_gateway_id nat_gateway_id
     *
     * @return $this
     */
    public function setNatGatewayId($nat_gateway_id)
    {
        $this->container['nat_gateway_id'] = $nat_gateway_id;

        return $this;
    }

    /**
     * Gets nat_ip_id
     *
     * @return string
     */
    public function getNatIpId()
    {
        return $this->container['nat_ip_id'];
    }

    /**
     * Sets nat_ip_id
     *
     * @param string $nat_ip_id nat_ip_id
     *
     * @return $this
     */
    public function setNatIpId($nat_ip_id)
    {
        $this->container['nat_ip_id'] = $nat_ip_id;

        return $this;
    }

    /**
     * Gets snat_entry_id
     *
     * @return string
     */
    public function getSnatEntryId()
    {
        return $this->container['snat_entry_id'];
    }

    /**
     * Sets snat_entry_id
     *
     * @param string $snat_entry_id snat_entry_id
     *
     * @return $this
     */
    public function setSnatEntryId($snat_entry_id)
    {
        $this->container['snat_entry_id'] = $snat_entry_id;

        return $this;
    }

    /**
     * Gets snat_entry_name
     *
     * @return string
     */
    public function getSnatEntryName()
    {
        return $this->container['snat_entry_name'];
    }

    /**
     * Sets snat_entry_name
     *
     * @param string $snat_entry_name snat_entry_name
     *
     * @return $this
     */
    public function setSnatEntryName($snat_entry_name)
    {
        $this->container['snat_entry_name'] = $snat_entry_name;

        return $this;
    }

    /**
     * Gets source_cidr
     *
     * @return string
     */
    public function getSourceCidr()
    {
        return $this->container['source_cidr'];
    }

    /**
     * Sets source_cidr
     *
     * @param string $source_cidr source_cidr
     *
     * @return $this
     */
    public function setSourceCidr($source_cidr)
    {
        $this->container['source_cidr'] = $source_cidr;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets subnet_id
     *
     * @return string
     */
    public function getSubnetId()
    {
        return $this->container['subnet_id'];
    }

    /**
     * Sets subnet_id
     *
     * @param string $subnet_id subnet_id
     *
     * @return $this
     */
    public function setSubnetId($subnet_id)
    {
        $this->container['subnet_id'] = $subnet_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

