<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Fwcenter\Model;

use ArrayAccess;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\ModelInterface;

class VpcFirewallInfoListForDescribeAclBackupOutput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'VpcFirewallInfoListForDescribeAclBackupOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'acl_rule_count' => 'int',
        'firewall_id' => 'string',
        'firewall_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'acl_rule_count' => 'int64',
        'firewall_id' => null,
        'firewall_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'acl_rule_count' => 'AclRuleCount',
        'firewall_id' => 'FirewallId',
        'firewall_name' => 'FirewallName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'acl_rule_count' => 'setAclRuleCount',
        'firewall_id' => 'setFirewallId',
        'firewall_name' => 'setFirewallName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'acl_rule_count' => 'getAclRuleCount',
        'firewall_id' => 'getFirewallId',
        'firewall_name' => 'getFirewallName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['acl_rule_count'] = isset($data['acl_rule_count']) ? $data['acl_rule_count'] : null;
        $this->container['firewall_id'] = isset($data['firewall_id']) ? $data['firewall_id'] : null;
        $this->container['firewall_name'] = isset($data['firewall_name']) ? $data['firewall_name'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets acl_rule_count
     *
     * @return int
     */
    public function getAclRuleCount()
    {
        return $this->container['acl_rule_count'];
    }

    /**
     * Sets acl_rule_count
     *
     * @param int $acl_rule_count acl_rule_count
     *
     * @return $this
     */
    public function setAclRuleCount($acl_rule_count)
    {
        $this->container['acl_rule_count'] = $acl_rule_count;

        return $this;
    }

    /**
     * Gets firewall_id
     *
     * @return string
     */
    public function getFirewallId()
    {
        return $this->container['firewall_id'];
    }

    /**
     * Sets firewall_id
     *
     * @param string $firewall_id firewall_id
     *
     * @return $this
     */
    public function setFirewallId($firewall_id)
    {
        $this->container['firewall_id'] = $firewall_id;

        return $this;
    }

    /**
     * Gets firewall_name
     *
     * @return string
     */
    public function getFirewallName()
    {
        return $this->container['firewall_name'];
    }

    /**
     * Sets firewall_name
     *
     * @param string $firewall_name firewall_name
     *
     * @return $this
     */
    public function setFirewallName($firewall_name)
    {
        $this->container['firewall_name'] = $firewall_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

