<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Id\Model;

use ArrayAccess;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\ModelInterface;

class InboundAuthConfigForBatchGetInboundAuthConfigOutput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'InboundAuthConfigForBatchGetInboundAuthConfigOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'api_key_auth_configs' => '\Volcengine\Id\Model\ApiKeyAuthConfigForBatchGetInboundAuthConfigOutput[]',
        'auth_type' => 'string',
        'config_name' => 'string',
        'created_at' => 'string',
        'description' => 'string',
        'inbound_auth_config_id' => 'string',
        'instance_id' => 'string',
        'jwt_auth_config' => '\Volcengine\Id\Model\JwtAuthConfigForBatchGetInboundAuthConfigOutput',
        'trn' => 'string',
        'updated_at' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'api_key_auth_configs' => null,
        'auth_type' => null,
        'config_name' => null,
        'created_at' => null,
        'description' => null,
        'inbound_auth_config_id' => null,
        'instance_id' => null,
        'jwt_auth_config' => null,
        'trn' => null,
        'updated_at' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'api_key_auth_configs' => 'ApiKeyAuthConfigs',
        'auth_type' => 'AuthType',
        'config_name' => 'ConfigName',
        'created_at' => 'CreatedAt',
        'description' => 'Description',
        'inbound_auth_config_id' => 'InboundAuthConfigId',
        'instance_id' => 'InstanceId',
        'jwt_auth_config' => 'JwtAuthConfig',
        'trn' => 'Trn',
        'updated_at' => 'UpdatedAt'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'api_key_auth_configs' => 'setApiKeyAuthConfigs',
        'auth_type' => 'setAuthType',
        'config_name' => 'setConfigName',
        'created_at' => 'setCreatedAt',
        'description' => 'setDescription',
        'inbound_auth_config_id' => 'setInboundAuthConfigId',
        'instance_id' => 'setInstanceId',
        'jwt_auth_config' => 'setJwtAuthConfig',
        'trn' => 'setTrn',
        'updated_at' => 'setUpdatedAt'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'api_key_auth_configs' => 'getApiKeyAuthConfigs',
        'auth_type' => 'getAuthType',
        'config_name' => 'getConfigName',
        'created_at' => 'getCreatedAt',
        'description' => 'getDescription',
        'inbound_auth_config_id' => 'getInboundAuthConfigId',
        'instance_id' => 'getInstanceId',
        'jwt_auth_config' => 'getJwtAuthConfig',
        'trn' => 'getTrn',
        'updated_at' => 'getUpdatedAt'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['api_key_auth_configs'] = isset($data['api_key_auth_configs']) ? $data['api_key_auth_configs'] : null;
        $this->container['auth_type'] = isset($data['auth_type']) ? $data['auth_type'] : null;
        $this->container['config_name'] = isset($data['config_name']) ? $data['config_name'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['inbound_auth_config_id'] = isset($data['inbound_auth_config_id']) ? $data['inbound_auth_config_id'] : null;
        $this->container['instance_id'] = isset($data['instance_id']) ? $data['instance_id'] : null;
        $this->container['jwt_auth_config'] = isset($data['jwt_auth_config']) ? $data['jwt_auth_config'] : null;
        $this->container['trn'] = isset($data['trn']) ? $data['trn'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets api_key_auth_configs
     *
     * @return \Volcengine\Id\Model\ApiKeyAuthConfigForBatchGetInboundAuthConfigOutput[]
     */
    public function getApiKeyAuthConfigs()
    {
        return $this->container['api_key_auth_configs'];
    }

    /**
     * Sets api_key_auth_configs
     *
     * @param \Volcengine\Id\Model\ApiKeyAuthConfigForBatchGetInboundAuthConfigOutput[] $api_key_auth_configs api_key_auth_configs
     *
     * @return $this
     */
    public function setApiKeyAuthConfigs($api_key_auth_configs)
    {
        $this->container['api_key_auth_configs'] = $api_key_auth_configs;

        return $this;
    }

    /**
     * Gets auth_type
     *
     * @return string
     */
    public function getAuthType()
    {
        return $this->container['auth_type'];
    }

    /**
     * Sets auth_type
     *
     * @param string $auth_type auth_type
     *
     * @return $this
     */
    public function setAuthType($auth_type)
    {
        $this->container['auth_type'] = $auth_type;

        return $this;
    }

    /**
     * Gets config_name
     *
     * @return string
     */
    public function getConfigName()
    {
        return $this->container['config_name'];
    }

    /**
     * Sets config_name
     *
     * @param string $config_name config_name
     *
     * @return $this
     */
    public function setConfigName($config_name)
    {
        $this->container['config_name'] = $config_name;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at created_at
     *
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets inbound_auth_config_id
     *
     * @return string
     */
    public function getInboundAuthConfigId()
    {
        return $this->container['inbound_auth_config_id'];
    }

    /**
     * Sets inbound_auth_config_id
     *
     * @param string $inbound_auth_config_id inbound_auth_config_id
     *
     * @return $this
     */
    public function setInboundAuthConfigId($inbound_auth_config_id)
    {
        $this->container['inbound_auth_config_id'] = $inbound_auth_config_id;

        return $this;
    }

    /**
     * Gets instance_id
     *
     * @return string
     */
    public function getInstanceId()
    {
        return $this->container['instance_id'];
    }

    /**
     * Sets instance_id
     *
     * @param string $instance_id instance_id
     *
     * @return $this
     */
    public function setInstanceId($instance_id)
    {
        $this->container['instance_id'] = $instance_id;

        return $this;
    }

    /**
     * Gets jwt_auth_config
     *
     * @return \Volcengine\Id\Model\JwtAuthConfigForBatchGetInboundAuthConfigOutput
     */
    public function getJwtAuthConfig()
    {
        return $this->container['jwt_auth_config'];
    }

    /**
     * Sets jwt_auth_config
     *
     * @param \Volcengine\Id\Model\JwtAuthConfigForBatchGetInboundAuthConfigOutput $jwt_auth_config jwt_auth_config
     *
     * @return $this
     */
    public function setJwtAuthConfig($jwt_auth_config)
    {
        $this->container['jwt_auth_config'] = $jwt_auth_config;

        return $this;
    }

    /**
     * Gets trn
     *
     * @return string
     */
    public function getTrn()
    {
        return $this->container['trn'];
    }

    /**
     * Sets trn
     *
     * @param string $trn trn
     *
     * @return $this
     */
    public function setTrn($trn)
    {
        $this->container['trn'] = $trn;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return string
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param string $updated_at updated_at
     *
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

