<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Vke\Model;

use ArrayAccess;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\ModelInterface;

class DataVolumeForCreateNodePoolInput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DataVolumeForCreateNodePoolInput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'extra_performance_iops' => 'int',
        'extra_performance_throughput_mb' => 'int',
        'extra_performance_type_id' => 'string',
        'file_system' => 'string',
        'mount_point' => 'string',
        'placement_group_id' => 'string',
        'size' => 'int',
        'snapshot_id' => 'string',
        'subgroup_number' => 'int',
        'type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'extra_performance_iops' => 'int32',
        'extra_performance_throughput_mb' => 'int32',
        'extra_performance_type_id' => null,
        'file_system' => null,
        'mount_point' => null,
        'placement_group_id' => null,
        'size' => 'int32',
        'snapshot_id' => null,
        'subgroup_number' => 'int32',
        'type' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'extra_performance_iops' => 'ExtraPerformanceIops',
        'extra_performance_throughput_mb' => 'ExtraPerformanceThroughputMb',
        'extra_performance_type_id' => 'ExtraPerformanceTypeId',
        'file_system' => 'FileSystem',
        'mount_point' => 'MountPoint',
        'placement_group_id' => 'PlacementGroupId',
        'size' => 'Size',
        'snapshot_id' => 'SnapshotId',
        'subgroup_number' => 'SubgroupNumber',
        'type' => 'Type'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'extra_performance_iops' => 'setExtraPerformanceIops',
        'extra_performance_throughput_mb' => 'setExtraPerformanceThroughputMb',
        'extra_performance_type_id' => 'setExtraPerformanceTypeId',
        'file_system' => 'setFileSystem',
        'mount_point' => 'setMountPoint',
        'placement_group_id' => 'setPlacementGroupId',
        'size' => 'setSize',
        'snapshot_id' => 'setSnapshotId',
        'subgroup_number' => 'setSubgroupNumber',
        'type' => 'setType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'extra_performance_iops' => 'getExtraPerformanceIops',
        'extra_performance_throughput_mb' => 'getExtraPerformanceThroughputMb',
        'extra_performance_type_id' => 'getExtraPerformanceTypeId',
        'file_system' => 'getFileSystem',
        'mount_point' => 'getMountPoint',
        'placement_group_id' => 'getPlacementGroupId',
        'size' => 'getSize',
        'snapshot_id' => 'getSnapshotId',
        'subgroup_number' => 'getSubgroupNumber',
        'type' => 'getType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const EXTRA_PERFORMANCE_TYPE_ID_BALANCE = 'Balance';
    const EXTRA_PERFORMANCE_TYPE_ID_IOPS = 'IOPS';
    const EXTRA_PERFORMANCE_TYPE_ID_THROUGHPUT = 'Throughput';
    const FILE_SYSTEM_EXT4 = 'Ext4';
    const FILE_SYSTEM_XFS = 'Xfs';
    const TYPE_ESSD = 'ESSD';
    const TYPE_ESSD_PL0 = 'ESSD_PL0';
    const TYPE_ESSD_FLEX_PL = 'ESSD_FlexPL';
    const TYPE_ULTRA_DISK = 'Ultra_Disk';
    const TYPE_TSSD_TL0 = 'TSSD_TL0';
    const TYPE_RSSD_RL0 = 'RSSD_RL0';
    const TYPE_LOCAL_SSD = 'LOCAL_SSD';
    const TYPE_LOCAL_HDD = 'LOCAL_HDD';
    const TYPE_LOCAL_SSD_SRIOV = 'LOCAL_SSD_SRIOV';
    const TYPE_LOCAL_LVM_SSD = 'LOCAL_LVM_SSD';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getExtraPerformanceTypeIdAllowableValues()
    {
        return [
            self::EXTRA_PERFORMANCE_TYPE_ID_BALANCE,
            self::EXTRA_PERFORMANCE_TYPE_ID_IOPS,
            self::EXTRA_PERFORMANCE_TYPE_ID_THROUGHPUT,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFileSystemAllowableValues()
    {
        return [
            self::FILE_SYSTEM_EXT4,
            self::FILE_SYSTEM_XFS,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_ESSD,
            self::TYPE_ESSD_PL0,
            self::TYPE_ESSD_FLEX_PL,
            self::TYPE_ULTRA_DISK,
            self::TYPE_TSSD_TL0,
            self::TYPE_RSSD_RL0,
            self::TYPE_LOCAL_SSD,
            self::TYPE_LOCAL_HDD,
            self::TYPE_LOCAL_SSD_SRIOV,
            self::TYPE_LOCAL_LVM_SSD,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->container['extra_performance_iops'] = isset($data['extra_performance_iops']) ? $data['extra_performance_iops'] : null;
        $this->container['extra_performance_throughput_mb'] = isset($data['extra_performance_throughput_mb']) ? $data['extra_performance_throughput_mb'] : null;
        $this->container['extra_performance_type_id'] = isset($data['extra_performance_type_id']) ? $data['extra_performance_type_id'] : null;
        $this->container['file_system'] = isset($data['file_system']) ? $data['file_system'] : null;
        $this->container['mount_point'] = isset($data['mount_point']) ? $data['mount_point'] : null;
        $this->container['placement_group_id'] = isset($data['placement_group_id']) ? $data['placement_group_id'] : null;
        $this->container['size'] = isset($data['size']) ? $data['size'] : null;
        $this->container['snapshot_id'] = isset($data['snapshot_id']) ? $data['snapshot_id'] : null;
        $this->container['subgroup_number'] = isset($data['subgroup_number']) ? $data['subgroup_number'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getExtraPerformanceTypeIdAllowableValues();
        if (!is_null($this->container['extra_performance_type_id']) && !in_array($this->container['extra_performance_type_id'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'extra_performance_type_id', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getFileSystemAllowableValues();
        if (!is_null($this->container['file_system']) && !in_array($this->container['file_system'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'file_system', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets extra_performance_iops
     *
     * @return int
     */
    public function getExtraPerformanceIops()
    {
        return $this->container['extra_performance_iops'];
    }

    /**
     * Sets extra_performance_iops
     *
     * @param int $extra_performance_iops extra_performance_iops
     *
     * @return $this
     */
    public function setExtraPerformanceIops($extra_performance_iops)
    {
        $this->container['extra_performance_iops'] = $extra_performance_iops;

        return $this;
    }

    /**
     * Gets extra_performance_throughput_mb
     *
     * @return int
     */
    public function getExtraPerformanceThroughputMb()
    {
        return $this->container['extra_performance_throughput_mb'];
    }

    /**
     * Sets extra_performance_throughput_mb
     *
     * @param int $extra_performance_throughput_mb extra_performance_throughput_mb
     *
     * @return $this
     */
    public function setExtraPerformanceThroughputMb($extra_performance_throughput_mb)
    {
        $this->container['extra_performance_throughput_mb'] = $extra_performance_throughput_mb;

        return $this;
    }

    /**
     * Gets extra_performance_type_id
     *
     * @return string
     */
    public function getExtraPerformanceTypeId()
    {
        return $this->container['extra_performance_type_id'];
    }

    /**
     * Sets extra_performance_type_id
     *
     * @param string $extra_performance_type_id extra_performance_type_id
     *
     * @return $this
     */
    public function setExtraPerformanceTypeId($extra_performance_type_id)
    {
        $allowedValues = $this->getExtraPerformanceTypeIdAllowableValues();
        if (!is_null($extra_performance_type_id) && !in_array($extra_performance_type_id, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'extra_performance_type_id', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['extra_performance_type_id'] = $extra_performance_type_id;

        return $this;
    }

    /**
     * Gets file_system
     *
     * @return string
     */
    public function getFileSystem()
    {
        return $this->container['file_system'];
    }

    /**
     * Sets file_system
     *
     * @param string $file_system file_system
     *
     * @return $this
     */
    public function setFileSystem($file_system)
    {
        $allowedValues = $this->getFileSystemAllowableValues();
        if (!is_null($file_system) && !in_array($file_system, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'file_system', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['file_system'] = $file_system;

        return $this;
    }

    /**
     * Gets mount_point
     *
     * @return string
     */
    public function getMountPoint()
    {
        return $this->container['mount_point'];
    }

    /**
     * Sets mount_point
     *
     * @param string $mount_point mount_point
     *
     * @return $this
     */
    public function setMountPoint($mount_point)
    {
        $this->container['mount_point'] = $mount_point;

        return $this;
    }

    /**
     * Gets placement_group_id
     *
     * @return string
     */
    public function getPlacementGroupId()
    {
        return $this->container['placement_group_id'];
    }

    /**
     * Sets placement_group_id
     *
     * @param string $placement_group_id placement_group_id
     *
     * @return $this
     */
    public function setPlacementGroupId($placement_group_id)
    {
        $this->container['placement_group_id'] = $placement_group_id;

        return $this;
    }

    /**
     * Gets size
     *
     * @return int
     */
    public function getSize()
    {
        return $this->container['size'];
    }

    /**
     * Sets size
     *
     * @param int $size size
     *
     * @return $this
     */
    public function setSize($size)
    {
        $this->container['size'] = $size;

        return $this;
    }

    /**
     * Gets snapshot_id
     *
     * @return string
     */
    public function getSnapshotId()
    {
        return $this->container['snapshot_id'];
    }

    /**
     * Sets snapshot_id
     *
     * @param string $snapshot_id snapshot_id
     *
     * @return $this
     */
    public function setSnapshotId($snapshot_id)
    {
        $this->container['snapshot_id'] = $snapshot_id;

        return $this;
    }

    /**
     * Gets subgroup_number
     *
     * @return int
     */
    public function getSubgroupNumber()
    {
        return $this->container['subgroup_number'];
    }

    /**
     * Sets subgroup_number
     *
     * @param int $subgroup_number subgroup_number
     *
     * @return $this
     */
    public function setSubgroupNumber($subgroup_number)
    {
        $this->container['subgroup_number'] = $subgroup_number;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return $this
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($type) && !in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

