<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Seccenter20240508\Model;

use ArrayAccess;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\ModelInterface;

class DataForListRaspConfigsOutput implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DataForListRaspConfigsOutput';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'all_process_inject' => 'bool',
        'blocks' => '\Volcengine\Seccenter20240508\Model\BlockForListRaspConfigsOutput[]',
        'filters' => '\Volcengine\Seccenter20240508\Model\FilterForListRaspConfigsOutput[]',
        'id' => 'string',
        'if_protect' => 'bool',
        'inject_config_list' => '\Volcengine\Seccenter20240508\Model\InjectConfigListForListRaspConfigsOutput[]',
        'local_project_inject' => 'bool',
        'name' => 'string',
        'protect_method' => 'string',
        'protected_agent_count' => 'int',
        'protected_process_count' => 'int',
        'range' => '\Volcengine\Seccenter20240508\Model\RangeForListRaspConfigsOutput',
        'runtime' => 'string',
        'switch' => '\Volcengine\Seccenter20240508\Model\SwitchForListRaspConfigsOutput',
        'to_be_protected_agent_count' => 'int',
        'to_be_protected_process_count' => 'int',
        'top_group_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'all_process_inject' => null,
        'blocks' => null,
        'filters' => null,
        'id' => null,
        'if_protect' => null,
        'inject_config_list' => null,
        'local_project_inject' => null,
        'name' => null,
        'protect_method' => null,
        'protected_agent_count' => 'int32',
        'protected_process_count' => 'int32',
        'range' => null,
        'runtime' => null,
        'switch' => null,
        'to_be_protected_agent_count' => 'int32',
        'to_be_protected_process_count' => 'int32',
        'top_group_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'all_process_inject' => 'AllProcessInject',
        'blocks' => 'Blocks',
        'filters' => 'Filters',
        'id' => 'ID',
        'if_protect' => 'IfProtect',
        'inject_config_list' => 'InjectConfigList',
        'local_project_inject' => 'LocalProjectInject',
        'name' => 'Name',
        'protect_method' => 'ProtectMethod',
        'protected_agent_count' => 'ProtectedAgentCount',
        'protected_process_count' => 'ProtectedProcessCount',
        'range' => 'Range',
        'runtime' => 'Runtime',
        'switch' => 'Switch',
        'to_be_protected_agent_count' => 'ToBeProtectedAgentCount',
        'to_be_protected_process_count' => 'ToBeProtectedProcessCount',
        'top_group_id' => 'TopGroupID'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'all_process_inject' => 'setAllProcessInject',
        'blocks' => 'setBlocks',
        'filters' => 'setFilters',
        'id' => 'setId',
        'if_protect' => 'setIfProtect',
        'inject_config_list' => 'setInjectConfigList',
        'local_project_inject' => 'setLocalProjectInject',
        'name' => 'setName',
        'protect_method' => 'setProtectMethod',
        'protected_agent_count' => 'setProtectedAgentCount',
        'protected_process_count' => 'setProtectedProcessCount',
        'range' => 'setRange',
        'runtime' => 'setRuntime',
        'switch' => 'setSwitch',
        'to_be_protected_agent_count' => 'setToBeProtectedAgentCount',
        'to_be_protected_process_count' => 'setToBeProtectedProcessCount',
        'top_group_id' => 'setTopGroupId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'all_process_inject' => 'getAllProcessInject',
        'blocks' => 'getBlocks',
        'filters' => 'getFilters',
        'id' => 'getId',
        'if_protect' => 'getIfProtect',
        'inject_config_list' => 'getInjectConfigList',
        'local_project_inject' => 'getLocalProjectInject',
        'name' => 'getName',
        'protect_method' => 'getProtectMethod',
        'protected_agent_count' => 'getProtectedAgentCount',
        'protected_process_count' => 'getProtectedProcessCount',
        'range' => 'getRange',
        'runtime' => 'getRuntime',
        'switch' => 'getSwitch',
        'to_be_protected_agent_count' => 'getToBeProtectedAgentCount',
        'to_be_protected_process_count' => 'getToBeProtectedProcessCount',
        'top_group_id' => 'getTopGroupId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['all_process_inject'] = isset($data['all_process_inject']) ? $data['all_process_inject'] : null;
        $this->container['blocks'] = isset($data['blocks']) ? $data['blocks'] : null;
        $this->container['filters'] = isset($data['filters']) ? $data['filters'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['if_protect'] = isset($data['if_protect']) ? $data['if_protect'] : null;
        $this->container['inject_config_list'] = isset($data['inject_config_list']) ? $data['inject_config_list'] : null;
        $this->container['local_project_inject'] = isset($data['local_project_inject']) ? $data['local_project_inject'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['protect_method'] = isset($data['protect_method']) ? $data['protect_method'] : null;
        $this->container['protected_agent_count'] = isset($data['protected_agent_count']) ? $data['protected_agent_count'] : null;
        $this->container['protected_process_count'] = isset($data['protected_process_count']) ? $data['protected_process_count'] : null;
        $this->container['range'] = isset($data['range']) ? $data['range'] : null;
        $this->container['runtime'] = isset($data['runtime']) ? $data['runtime'] : null;
        $this->container['switch'] = isset($data['switch']) ? $data['switch'] : null;
        $this->container['to_be_protected_agent_count'] = isset($data['to_be_protected_agent_count']) ? $data['to_be_protected_agent_count'] : null;
        $this->container['to_be_protected_process_count'] = isset($data['to_be_protected_process_count']) ? $data['to_be_protected_process_count'] : null;
        $this->container['top_group_id'] = isset($data['top_group_id']) ? $data['top_group_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets all_process_inject
     *
     * @return bool
     */
    public function getAllProcessInject()
    {
        return $this->container['all_process_inject'];
    }

    /**
     * Sets all_process_inject
     *
     * @param bool $all_process_inject all_process_inject
     *
     * @return $this
     */
    public function setAllProcessInject($all_process_inject)
    {
        $this->container['all_process_inject'] = $all_process_inject;

        return $this;
    }

    /**
     * Gets blocks
     *
     * @return \Volcengine\Seccenter20240508\Model\BlockForListRaspConfigsOutput[]
     */
    public function getBlocks()
    {
        return $this->container['blocks'];
    }

    /**
     * Sets blocks
     *
     * @param \Volcengine\Seccenter20240508\Model\BlockForListRaspConfigsOutput[] $blocks blocks
     *
     * @return $this
     */
    public function setBlocks($blocks)
    {
        $this->container['blocks'] = $blocks;

        return $this;
    }

    /**
     * Gets filters
     *
     * @return \Volcengine\Seccenter20240508\Model\FilterForListRaspConfigsOutput[]
     */
    public function getFilters()
    {
        return $this->container['filters'];
    }

    /**
     * Sets filters
     *
     * @param \Volcengine\Seccenter20240508\Model\FilterForListRaspConfigsOutput[] $filters filters
     *
     * @return $this
     */
    public function setFilters($filters)
    {
        $this->container['filters'] = $filters;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets if_protect
     *
     * @return bool
     */
    public function getIfProtect()
    {
        return $this->container['if_protect'];
    }

    /**
     * Sets if_protect
     *
     * @param bool $if_protect if_protect
     *
     * @return $this
     */
    public function setIfProtect($if_protect)
    {
        $this->container['if_protect'] = $if_protect;

        return $this;
    }

    /**
     * Gets inject_config_list
     *
     * @return \Volcengine\Seccenter20240508\Model\InjectConfigListForListRaspConfigsOutput[]
     */
    public function getInjectConfigList()
    {
        return $this->container['inject_config_list'];
    }

    /**
     * Sets inject_config_list
     *
     * @param \Volcengine\Seccenter20240508\Model\InjectConfigListForListRaspConfigsOutput[] $inject_config_list inject_config_list
     *
     * @return $this
     */
    public function setInjectConfigList($inject_config_list)
    {
        $this->container['inject_config_list'] = $inject_config_list;

        return $this;
    }

    /**
     * Gets local_project_inject
     *
     * @return bool
     */
    public function getLocalProjectInject()
    {
        return $this->container['local_project_inject'];
    }

    /**
     * Sets local_project_inject
     *
     * @param bool $local_project_inject local_project_inject
     *
     * @return $this
     */
    public function setLocalProjectInject($local_project_inject)
    {
        $this->container['local_project_inject'] = $local_project_inject;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets protect_method
     *
     * @return string
     */
    public function getProtectMethod()
    {
        return $this->container['protect_method'];
    }

    /**
     * Sets protect_method
     *
     * @param string $protect_method protect_method
     *
     * @return $this
     */
    public function setProtectMethod($protect_method)
    {
        $this->container['protect_method'] = $protect_method;

        return $this;
    }

    /**
     * Gets protected_agent_count
     *
     * @return int
     */
    public function getProtectedAgentCount()
    {
        return $this->container['protected_agent_count'];
    }

    /**
     * Sets protected_agent_count
     *
     * @param int $protected_agent_count protected_agent_count
     *
     * @return $this
     */
    public function setProtectedAgentCount($protected_agent_count)
    {
        $this->container['protected_agent_count'] = $protected_agent_count;

        return $this;
    }

    /**
     * Gets protected_process_count
     *
     * @return int
     */
    public function getProtectedProcessCount()
    {
        return $this->container['protected_process_count'];
    }

    /**
     * Sets protected_process_count
     *
     * @param int $protected_process_count protected_process_count
     *
     * @return $this
     */
    public function setProtectedProcessCount($protected_process_count)
    {
        $this->container['protected_process_count'] = $protected_process_count;

        return $this;
    }

    /**
     * Gets range
     *
     * @return \Volcengine\Seccenter20240508\Model\RangeForListRaspConfigsOutput
     */
    public function getRange()
    {
        return $this->container['range'];
    }

    /**
     * Sets range
     *
     * @param \Volcengine\Seccenter20240508\Model\RangeForListRaspConfigsOutput $range range
     *
     * @return $this
     */
    public function setRange($range)
    {
        $this->container['range'] = $range;

        return $this;
    }

    /**
     * Gets runtime
     *
     * @return string
     */
    public function getRuntime()
    {
        return $this->container['runtime'];
    }

    /**
     * Sets runtime
     *
     * @param string $runtime runtime
     *
     * @return $this
     */
    public function setRuntime($runtime)
    {
        $this->container['runtime'] = $runtime;

        return $this;
    }

    /**
     * Gets switch
     *
     * @return \Volcengine\Seccenter20240508\Model\SwitchForListRaspConfigsOutput
     */
    public function getSwitch()
    {
        return $this->container['switch'];
    }

    /**
     * Sets switch
     *
     * @param \Volcengine\Seccenter20240508\Model\SwitchForListRaspConfigsOutput $switch switch
     *
     * @return $this
     */
    public function setSwitch($switch)
    {
        $this->container['switch'] = $switch;

        return $this;
    }

    /**
     * Gets to_be_protected_agent_count
     *
     * @return int
     */
    public function getToBeProtectedAgentCount()
    {
        return $this->container['to_be_protected_agent_count'];
    }

    /**
     * Sets to_be_protected_agent_count
     *
     * @param int $to_be_protected_agent_count to_be_protected_agent_count
     *
     * @return $this
     */
    public function setToBeProtectedAgentCount($to_be_protected_agent_count)
    {
        $this->container['to_be_protected_agent_count'] = $to_be_protected_agent_count;

        return $this;
    }

    /**
     * Gets to_be_protected_process_count
     *
     * @return int
     */
    public function getToBeProtectedProcessCount()
    {
        return $this->container['to_be_protected_process_count'];
    }

    /**
     * Sets to_be_protected_process_count
     *
     * @param int $to_be_protected_process_count to_be_protected_process_count
     *
     * @return $this
     */
    public function setToBeProtectedProcessCount($to_be_protected_process_count)
    {
        $this->container['to_be_protected_process_count'] = $to_be_protected_process_count;

        return $this;
    }

    /**
     * Gets top_group_id
     *
     * @return string
     */
    public function getTopGroupId()
    {
        return $this->container['top_group_id'];
    }

    /**
     * Sets top_group_id
     *
     * @param string $top_group_id top_group_id
     *
     * @return $this
     */
    public function setTopGroupId($top_group_id)
    {
        $this->container['top_group_id'] = $top_group_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

