<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Seccenter20240508\Model;

use ArrayAccess;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\ModelInterface;

class GetPolicyStatisticsResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'GetPolicyStatisticsResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'cluster_hardening_stats' => '\Volcengine\Seccenter20240508\Model\ClusterHardeningStatsForGetPolicyStatisticsOutput',
        'clusters_without_varmor_count' => 'int',
        'policy_status_stats' => '\Volcengine\Seccenter20240508\Model\PolicyStatusStatForGetPolicyStatisticsOutput[]',
        'update_time' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'cluster_hardening_stats' => null,
        'clusters_without_varmor_count' => 'int64',
        'policy_status_stats' => null,
        'update_time' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'cluster_hardening_stats' => 'ClusterHardeningStats',
        'clusters_without_varmor_count' => 'ClustersWithoutVarmorCount',
        'policy_status_stats' => 'PolicyStatusStats',
        'update_time' => 'UpdateTime'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'cluster_hardening_stats' => 'setClusterHardeningStats',
        'clusters_without_varmor_count' => 'setClustersWithoutVarmorCount',
        'policy_status_stats' => 'setPolicyStatusStats',
        'update_time' => 'setUpdateTime'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'cluster_hardening_stats' => 'getClusterHardeningStats',
        'clusters_without_varmor_count' => 'getClustersWithoutVarmorCount',
        'policy_status_stats' => 'getPolicyStatusStats',
        'update_time' => 'getUpdateTime'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['cluster_hardening_stats'] = isset($data['cluster_hardening_stats']) ? $data['cluster_hardening_stats'] : null;
        $this->container['clusters_without_varmor_count'] = isset($data['clusters_without_varmor_count']) ? $data['clusters_without_varmor_count'] : null;
        $this->container['policy_status_stats'] = isset($data['policy_status_stats']) ? $data['policy_status_stats'] : null;
        $this->container['update_time'] = isset($data['update_time']) ? $data['update_time'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets cluster_hardening_stats
     *
     * @return \Volcengine\Seccenter20240508\Model\ClusterHardeningStatsForGetPolicyStatisticsOutput
     */
    public function getClusterHardeningStats()
    {
        return $this->container['cluster_hardening_stats'];
    }

    /**
     * Sets cluster_hardening_stats
     *
     * @param \Volcengine\Seccenter20240508\Model\ClusterHardeningStatsForGetPolicyStatisticsOutput $cluster_hardening_stats cluster_hardening_stats
     *
     * @return $this
     */
    public function setClusterHardeningStats($cluster_hardening_stats)
    {
        $this->container['cluster_hardening_stats'] = $cluster_hardening_stats;

        return $this;
    }

    /**
     * Gets clusters_without_varmor_count
     *
     * @return int
     */
    public function getClustersWithoutVarmorCount()
    {
        return $this->container['clusters_without_varmor_count'];
    }

    /**
     * Sets clusters_without_varmor_count
     *
     * @param int $clusters_without_varmor_count clusters_without_varmor_count
     *
     * @return $this
     */
    public function setClustersWithoutVarmorCount($clusters_without_varmor_count)
    {
        $this->container['clusters_without_varmor_count'] = $clusters_without_varmor_count;

        return $this;
    }

    /**
     * Gets policy_status_stats
     *
     * @return \Volcengine\Seccenter20240508\Model\PolicyStatusStatForGetPolicyStatisticsOutput[]
     */
    public function getPolicyStatusStats()
    {
        return $this->container['policy_status_stats'];
    }

    /**
     * Sets policy_status_stats
     *
     * @param \Volcengine\Seccenter20240508\Model\PolicyStatusStatForGetPolicyStatisticsOutput[] $policy_status_stats policy_status_stats
     *
     * @return $this
     */
    public function setPolicyStatusStats($policy_status_stats)
    {
        $this->container['policy_status_stats'] = $policy_status_stats;

        return $this;
    }

    /**
     * Gets update_time
     *
     * @return string
     */
    public function getUpdateTime()
    {
        return $this->container['update_time'];
    }

    /**
     * Sets update_time
     *
     * @param string $update_time update_time
     *
     * @return $this
     */
    public function setUpdateTime($update_time)
    {
        $this->container['update_time'] = $update_time;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

