<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Seccenter20240508\Model;

use ArrayAccess;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\ModelInterface;

class HandleAIVulnRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'HandleAIVulnRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'after_status' => 'string',
        'before_status' => 'string',
        'cwpp_id_list' => 'string[]',
        'is_real_risk_vul' => 'bool',
        'reason' => 'string',
        'session_id_list' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'after_status' => null,
        'before_status' => null,
        'cwpp_id_list' => null,
        'is_real_risk_vul' => null,
        'reason' => null,
        'session_id_list' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'after_status' => 'AfterStatus',
        'before_status' => 'BeforeStatus',
        'cwpp_id_list' => 'CwppIDList',
        'is_real_risk_vul' => 'IsRealRiskVul',
        'reason' => 'Reason',
        'session_id_list' => 'SessionIDList'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'after_status' => 'setAfterStatus',
        'before_status' => 'setBeforeStatus',
        'cwpp_id_list' => 'setCwppIdList',
        'is_real_risk_vul' => 'setIsRealRiskVul',
        'reason' => 'setReason',
        'session_id_list' => 'setSessionIdList'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'after_status' => 'getAfterStatus',
        'before_status' => 'getBeforeStatus',
        'cwpp_id_list' => 'getCwppIdList',
        'is_real_risk_vul' => 'getIsRealRiskVul',
        'reason' => 'getReason',
        'session_id_list' => 'getSessionIdList'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['after_status'] = isset($data['after_status']) ? $data['after_status'] : null;
        $this->container['before_status'] = isset($data['before_status']) ? $data['before_status'] : null;
        $this->container['cwpp_id_list'] = isset($data['cwpp_id_list']) ? $data['cwpp_id_list'] : null;
        $this->container['is_real_risk_vul'] = isset($data['is_real_risk_vul']) ? $data['is_real_risk_vul'] : null;
        $this->container['reason'] = isset($data['reason']) ? $data['reason'] : null;
        $this->container['session_id_list'] = isset($data['session_id_list']) ? $data['session_id_list'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets after_status
     *
     * @return string
     */
    public function getAfterStatus()
    {
        return $this->container['after_status'];
    }

    /**
     * Sets after_status
     *
     * @param string $after_status after_status
     *
     * @return $this
     */
    public function setAfterStatus($after_status)
    {
        $this->container['after_status'] = $after_status;

        return $this;
    }

    /**
     * Gets before_status
     *
     * @return string
     */
    public function getBeforeStatus()
    {
        return $this->container['before_status'];
    }

    /**
     * Sets before_status
     *
     * @param string $before_status before_status
     *
     * @return $this
     */
    public function setBeforeStatus($before_status)
    {
        $this->container['before_status'] = $before_status;

        return $this;
    }

    /**
     * Gets cwpp_id_list
     *
     * @return string[]
     */
    public function getCwppIdList()
    {
        return $this->container['cwpp_id_list'];
    }

    /**
     * Sets cwpp_id_list
     *
     * @param string[] $cwpp_id_list cwpp_id_list
     *
     * @return $this
     */
    public function setCwppIdList($cwpp_id_list)
    {
        $this->container['cwpp_id_list'] = $cwpp_id_list;

        return $this;
    }

    /**
     * Gets is_real_risk_vul
     *
     * @return bool
     */
    public function getIsRealRiskVul()
    {
        return $this->container['is_real_risk_vul'];
    }

    /**
     * Sets is_real_risk_vul
     *
     * @param bool $is_real_risk_vul is_real_risk_vul
     *
     * @return $this
     */
    public function setIsRealRiskVul($is_real_risk_vul)
    {
        $this->container['is_real_risk_vul'] = $is_real_risk_vul;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string $reason reason
     *
     * @return $this
     */
    public function setReason($reason)
    {
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets session_id_list
     *
     * @return string[]
     */
    public function getSessionIdList()
    {
        return $this->container['session_id_list'];
    }

    /**
     * Sets session_id_list
     *
     * @param string[] $session_id_list session_id_list
     *
     * @return $this
     */
    public function setSessionIdList($session_id_list)
    {
        $this->container['session_id_list'] = $session_id_list;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

