<?php

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Mcdn\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Volcengine\Common\ApiException;
use Volcengine\Common\Configuration;
use Volcengine\Common\HeaderSelector;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\Utils;
use Volcengine\Common\ApiClient;

class MCDNApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var ApiClient
     */
    protected $apiClient;

    /**
     * @param ClientInterface|null $client
     * @param Configuration|null $config
     * @param HeaderSelector|null $selector
     * @param ApiClient|null $apiClient
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        ApiClient $apiClient = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->apiClient = $apiClient ?: new ApiClient($this->config, $this->client);
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    public function addDnsScheduleStaticWeight($body = null)
    {
        list($response) = $this->addDnsScheduleStaticWeightWithHttpInfo($body);
        return $response;
    }

    public function addDnsScheduleStaticWeightWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\AddDnsScheduleStaticWeightResponse';
        $request = $this->addDnsScheduleStaticWeightRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function addDnsScheduleStaticWeightAsync($body = null)
    {
        return $this->addDnsScheduleStaticWeightAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function addDnsScheduleStaticWeightAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\AddDnsScheduleStaticWeightResponse';
        $request = $this->addDnsScheduleStaticWeightRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function addDnsScheduleStaticWeightRequest($body)
    {
        $resourcePath = '/AddDnsScheduleStaticWeight/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function deleteDnsScheduleStaticWeight($body = null)
    {
        list($response) = $this->deleteDnsScheduleStaticWeightWithHttpInfo($body);
        return $response;
    }

    public function deleteDnsScheduleStaticWeightWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DeleteDnsScheduleStaticWeightResponse';
        $request = $this->deleteDnsScheduleStaticWeightRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function deleteDnsScheduleStaticWeightAsync($body = null)
    {
        return $this->deleteDnsScheduleStaticWeightAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function deleteDnsScheduleStaticWeightAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DeleteDnsScheduleStaticWeightResponse';
        $request = $this->deleteDnsScheduleStaticWeightRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function deleteDnsScheduleStaticWeightRequest($body)
    {
        $resourcePath = '/DeleteDnsScheduleStaticWeight/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeAlertStrategy($body = null)
    {
        list($response) = $this->describeAlertStrategyWithHttpInfo($body);
        return $response;
    }

    public function describeAlertStrategyWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeAlertStrategyResponse';
        $request = $this->describeAlertStrategyRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeAlertStrategyAsync($body = null)
    {
        return $this->describeAlertStrategyAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeAlertStrategyAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeAlertStrategyResponse';
        $request = $this->describeAlertStrategyRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeAlertStrategyRequest($body)
    {
        $resourcePath = '/DescribeAlertStrategy/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeCdnAccessLog($body = null)
    {
        list($response) = $this->describeCdnAccessLogWithHttpInfo($body);
        return $response;
    }

    public function describeCdnAccessLogWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnAccessLogResponse';
        $request = $this->describeCdnAccessLogRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeCdnAccessLogAsync($body = null)
    {
        return $this->describeCdnAccessLogAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeCdnAccessLogAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnAccessLogResponse';
        $request = $this->describeCdnAccessLogRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeCdnAccessLogRequest($body)
    {
        $resourcePath = '/DescribeCdnAccessLog/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeCdnDataOffline($body = null)
    {
        list($response) = $this->describeCdnDataOfflineWithHttpInfo($body);
        return $response;
    }

    public function describeCdnDataOfflineWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnDataOfflineResponse';
        $request = $this->describeCdnDataOfflineRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeCdnDataOfflineAsync($body = null)
    {
        return $this->describeCdnDataOfflineAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeCdnDataOfflineAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnDataOfflineResponse';
        $request = $this->describeCdnDataOfflineRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeCdnDataOfflineRequest($body)
    {
        $resourcePath = '/DescribeCdnDataOffline/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeCdnOriginDataOffline($body = null)
    {
        list($response) = $this->describeCdnOriginDataOfflineWithHttpInfo($body);
        return $response;
    }

    public function describeCdnOriginDataOfflineWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnOriginDataOfflineResponse';
        $request = $this->describeCdnOriginDataOfflineRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeCdnOriginDataOfflineAsync($body = null)
    {
        return $this->describeCdnOriginDataOfflineAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeCdnOriginDataOfflineAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnOriginDataOfflineResponse';
        $request = $this->describeCdnOriginDataOfflineRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeCdnOriginDataOfflineRequest($body)
    {
        $resourcePath = '/DescribeCdnOriginDataOffline/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeCdnRegionAndIsp($body = null)
    {
        list($response) = $this->describeCdnRegionAndIspWithHttpInfo($body);
        return $response;
    }

    public function describeCdnRegionAndIspWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnRegionAndIspResponse';
        $request = $this->describeCdnRegionAndIspRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeCdnRegionAndIspAsync($body = null)
    {
        return $this->describeCdnRegionAndIspAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeCdnRegionAndIspAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnRegionAndIspResponse';
        $request = $this->describeCdnRegionAndIspRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeCdnRegionAndIspRequest($body)
    {
        $resourcePath = '/DescribeCdnRegionAndIsp/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeCdnTopIp($body = null)
    {
        list($response) = $this->describeCdnTopIpWithHttpInfo($body);
        return $response;
    }

    public function describeCdnTopIpWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnTopIpResponse';
        $request = $this->describeCdnTopIpRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeCdnTopIpAsync($body = null)
    {
        return $this->describeCdnTopIpAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeCdnTopIpAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnTopIpResponse';
        $request = $this->describeCdnTopIpRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeCdnTopIpRequest($body)
    {
        $resourcePath = '/DescribeCdnTopIp/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeCdnTopUrl($body = null)
    {
        list($response) = $this->describeCdnTopUrlWithHttpInfo($body);
        return $response;
    }

    public function describeCdnTopUrlWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnTopUrlResponse';
        $request = $this->describeCdnTopUrlRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeCdnTopUrlAsync($body = null)
    {
        return $this->describeCdnTopUrlAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeCdnTopUrlAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeCdnTopUrlResponse';
        $request = $this->describeCdnTopUrlRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeCdnTopUrlRequest($body)
    {
        $resourcePath = '/DescribeCdnTopUrl/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeContentQuota($body = null)
    {
        list($response) = $this->describeContentQuotaWithHttpInfo($body);
        return $response;
    }

    public function describeContentQuotaWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeContentQuotaResponse';
        $request = $this->describeContentQuotaRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeContentQuotaAsync($body = null)
    {
        return $this->describeContentQuotaAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeContentQuotaAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeContentQuotaResponse';
        $request = $this->describeContentQuotaRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeContentQuotaRequest($body)
    {
        $resourcePath = '/DescribeContentQuota/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeContentTaskByTaskId($body = null)
    {
        list($response) = $this->describeContentTaskByTaskIdWithHttpInfo($body);
        return $response;
    }

    public function describeContentTaskByTaskIdWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeContentTaskByTaskIdResponse';
        $request = $this->describeContentTaskByTaskIdRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeContentTaskByTaskIdAsync($body = null)
    {
        return $this->describeContentTaskByTaskIdAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeContentTaskByTaskIdAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeContentTaskByTaskIdResponse';
        $request = $this->describeContentTaskByTaskIdRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeContentTaskByTaskIdRequest($body)
    {
        $resourcePath = '/DescribeContentTaskByTaskId/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeDnsSchedule($body = null)
    {
        list($response) = $this->describeDnsScheduleWithHttpInfo($body);
        return $response;
    }

    public function describeDnsScheduleWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeDnsScheduleResponse';
        $request = $this->describeDnsScheduleRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeDnsScheduleAsync($body = null)
    {
        return $this->describeDnsScheduleAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeDnsScheduleAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeDnsScheduleResponse';
        $request = $this->describeDnsScheduleRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeDnsScheduleRequest($body)
    {
        $resourcePath = '/DescribeDnsSchedule/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeDnsScheduleActiveWeights($body = null)
    {
        list($response) = $this->describeDnsScheduleActiveWeightsWithHttpInfo($body);
        return $response;
    }

    public function describeDnsScheduleActiveWeightsWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeDnsScheduleActiveWeightsResponse';
        $request = $this->describeDnsScheduleActiveWeightsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeDnsScheduleActiveWeightsAsync($body = null)
    {
        return $this->describeDnsScheduleActiveWeightsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeDnsScheduleActiveWeightsAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeDnsScheduleActiveWeightsResponse';
        $request = $this->describeDnsScheduleActiveWeightsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeDnsScheduleActiveWeightsRequest($body)
    {
        $resourcePath = '/DescribeDnsScheduleActiveWeights/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function describeDnsScheduleStaticWeights($body = null)
    {
        list($response) = $this->describeDnsScheduleStaticWeightsWithHttpInfo($body);
        return $response;
    }

    public function describeDnsScheduleStaticWeightsWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeDnsScheduleStaticWeightsResponse';
        $request = $this->describeDnsScheduleStaticWeightsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function describeDnsScheduleStaticWeightsAsync($body = null)
    {
        return $this->describeDnsScheduleStaticWeightsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function describeDnsScheduleStaticWeightsAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DescribeDnsScheduleStaticWeightsResponse';
        $request = $this->describeDnsScheduleStaticWeightsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function describeDnsScheduleStaticWeightsRequest($body)
    {
        $resourcePath = '/DescribeDnsScheduleStaticWeights/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function disableDnsScheduleDomain($body = null)
    {
        list($response) = $this->disableDnsScheduleDomainWithHttpInfo($body);
        return $response;
    }

    public function disableDnsScheduleDomainWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DisableDnsScheduleDomainResponse';
        $request = $this->disableDnsScheduleDomainRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function disableDnsScheduleDomainAsync($body = null)
    {
        return $this->disableDnsScheduleDomainAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function disableDnsScheduleDomainAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\DisableDnsScheduleDomainResponse';
        $request = $this->disableDnsScheduleDomainRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function disableDnsScheduleDomainRequest($body)
    {
        $resourcePath = '/DisableDnsScheduleDomain/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function enableDnsScheduleDomain($body = null)
    {
        list($response) = $this->enableDnsScheduleDomainWithHttpInfo($body);
        return $response;
    }

    public function enableDnsScheduleDomainWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\EnableDnsScheduleDomainResponse';
        $request = $this->enableDnsScheduleDomainRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function enableDnsScheduleDomainAsync($body = null)
    {
        return $this->enableDnsScheduleDomainAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function enableDnsScheduleDomainAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\EnableDnsScheduleDomainResponse';
        $request = $this->enableDnsScheduleDomainRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function enableDnsScheduleDomainRequest($body)
    {
        $resourcePath = '/EnableDnsScheduleDomain/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function listAlertMetaMetrics($body = null)
    {
        list($response) = $this->listAlertMetaMetricsWithHttpInfo($body);
        return $response;
    }

    public function listAlertMetaMetricsWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListAlertMetaMetricsResponse';
        $request = $this->listAlertMetaMetricsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function listAlertMetaMetricsAsync($body = null)
    {
        return $this->listAlertMetaMetricsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function listAlertMetaMetricsAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListAlertMetaMetricsResponse';
        $request = $this->listAlertMetaMetricsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function listAlertMetaMetricsRequest($body)
    {
        $resourcePath = '/ListAlertMetaMetrics/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function listAlertStrategies($body = null)
    {
        list($response) = $this->listAlertStrategiesWithHttpInfo($body);
        return $response;
    }

    public function listAlertStrategiesWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListAlertStrategiesResponse';
        $request = $this->listAlertStrategiesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function listAlertStrategiesAsync($body = null)
    {
        return $this->listAlertStrategiesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function listAlertStrategiesAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListAlertStrategiesResponse';
        $request = $this->listAlertStrategiesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function listAlertStrategiesRequest($body)
    {
        $resourcePath = '/ListAlertStrategies/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function listCdnDomains($body = null)
    {
        list($response) = $this->listCdnDomainsWithHttpInfo($body);
        return $response;
    }

    public function listCdnDomainsWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListCdnDomainsResponse';
        $request = $this->listCdnDomainsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function listCdnDomainsAsync($body = null)
    {
        return $this->listCdnDomainsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function listCdnDomainsAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListCdnDomainsResponse';
        $request = $this->listCdnDomainsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function listCdnDomainsRequest($body)
    {
        $resourcePath = '/ListCdnDomains/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function listCloudAccounts($body = null)
    {
        list($response) = $this->listCloudAccountsWithHttpInfo($body);
        return $response;
    }

    public function listCloudAccountsWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListCloudAccountsResponse';
        $request = $this->listCloudAccountsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function listCloudAccountsAsync($body = null)
    {
        return $this->listCloudAccountsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function listCloudAccountsAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListCloudAccountsResponse';
        $request = $this->listCloudAccountsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function listCloudAccountsRequest($body)
    {
        $resourcePath = '/ListCloudAccounts/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function listContentTasks($body = null)
    {
        list($response) = $this->listContentTasksWithHttpInfo($body);
        return $response;
    }

    public function listContentTasksWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListContentTasksResponse';
        $request = $this->listContentTasksRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function listContentTasksAsync($body = null)
    {
        return $this->listContentTasksAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function listContentTasksAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListContentTasksResponse';
        $request = $this->listContentTasksRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function listContentTasksRequest($body)
    {
        $resourcePath = '/ListContentTasks/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function listDnsSchedules($body = null)
    {
        list($response) = $this->listDnsSchedulesWithHttpInfo($body);
        return $response;
    }

    public function listDnsSchedulesWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListDnsSchedulesResponse';
        $request = $this->listDnsSchedulesRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function listDnsSchedulesAsync($body = null)
    {
        return $this->listDnsSchedulesAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function listDnsSchedulesAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListDnsSchedulesResponse';
        $request = $this->listDnsSchedulesRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function listDnsSchedulesRequest($body)
    {
        $resourcePath = '/ListDnsSchedules/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function listVendorContentTask($body = null)
    {
        list($response) = $this->listVendorContentTaskWithHttpInfo($body);
        return $response;
    }

    public function listVendorContentTaskWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListVendorContentTaskResponse';
        $request = $this->listVendorContentTaskRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function listVendorContentTaskAsync($body = null)
    {
        return $this->listVendorContentTaskAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function listVendorContentTaskAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListVendorContentTaskResponse';
        $request = $this->listVendorContentTaskRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function listVendorContentTaskRequest($body)
    {
        $resourcePath = '/ListVendorContentTask/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function listViews($body = null)
    {
        list($response) = $this->listViewsWithHttpInfo($body);
        return $response;
    }

    public function listViewsWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListViewsResponse';
        $request = $this->listViewsRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function listViewsAsync($body = null)
    {
        return $this->listViewsAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function listViewsAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\ListViewsResponse';
        $request = $this->listViewsRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function listViewsRequest($body)
    {
        $resourcePath = '/ListViews/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function submitOverseaPreloadTask($body = null)
    {
        list($response) = $this->submitOverseaPreloadTaskWithHttpInfo($body);
        return $response;
    }

    public function submitOverseaPreloadTaskWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\SubmitOverseaPreloadTaskResponse';
        $request = $this->submitOverseaPreloadTaskRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function submitOverseaPreloadTaskAsync($body = null)
    {
        return $this->submitOverseaPreloadTaskAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function submitOverseaPreloadTaskAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\SubmitOverseaPreloadTaskResponse';
        $request = $this->submitOverseaPreloadTaskRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function submitOverseaPreloadTaskRequest($body)
    {
        $resourcePath = '/SubmitOverseaPreloadTask/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function submitPreloadTask($body = null)
    {
        list($response) = $this->submitPreloadTaskWithHttpInfo($body);
        return $response;
    }

    public function submitPreloadTaskWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\SubmitPreloadTaskResponse';
        $request = $this->submitPreloadTaskRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function submitPreloadTaskAsync($body = null)
    {
        return $this->submitPreloadTaskAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function submitPreloadTaskAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\SubmitPreloadTaskResponse';
        $request = $this->submitPreloadTaskRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function submitPreloadTaskRequest($body)
    {
        $resourcePath = '/SubmitPreloadTask/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function submitRefreshTask($body = null)
    {
        list($response) = $this->submitRefreshTaskWithHttpInfo($body);
        return $response;
    }

    public function submitRefreshTaskWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\SubmitRefreshTaskResponse';
        $request = $this->submitRefreshTaskRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function submitRefreshTaskAsync($body = null)
    {
        return $this->submitRefreshTaskAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function submitRefreshTaskAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\SubmitRefreshTaskResponse';
        $request = $this->submitRefreshTaskRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function submitRefreshTaskRequest($body)
    {
        $resourcePath = '/SubmitRefreshTask/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }

    public function updateDnsScheduleStaticWeight($body = null)
    {
        list($response) = $this->updateDnsScheduleStaticWeightWithHttpInfo($body);
        return $response;
    }

    public function updateDnsScheduleStaticWeightWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\UpdateDnsScheduleStaticWeightResponse';
        $request = $this->updateDnsScheduleStaticWeightRequest($body);

        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType);
    }

    public function updateDnsScheduleStaticWeightAsync($body = null)
    {
        return $this->updateDnsScheduleStaticWeightAsyncWithHttpInfo($body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    public function updateDnsScheduleStaticWeightAsyncWithHttpInfo($body)
    {
        $returnType = '\Volcengine\Mcdn\Model\UpdateDnsScheduleStaticWeightResponse';
        $request = $this->updateDnsScheduleStaticWeightRequest($body);
        return $this->apiClient->callApi($body, $request['resourcePath'], $request['method'], $request['headers'], $returnType, true);
    }

    protected function updateDnsScheduleStaticWeightRequest($body)
    {
        $resourcePath = '/UpdateDnsScheduleStaticWeight/2022-03-01/mcdn/post/application_json/';
        $queryParams = [];
        $httpBody = $body;

        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            ['application/json']
        );

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        if ($this->config->getHost()) {
            $defaultHeaders['Host'] = $this->config->getHost();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headers
        );

        $paths = explode("/", $resourcePath);
        $service = $paths[3];
        $method = strtoupper($paths[4]);

        return ['resourcePath' => $resourcePath, 'headers' => $headers, 'method' => $method];
    }


    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
