<?php
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Volcengine\Transitrouter\Model;

use ArrayAccess;
use Volcengine\Common\ObjectSerializer;
use Volcengine\Common\ModelInterface;

class DescribeTransitRouterBandwidthPackagesRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'DescribeTransitRouterBandwidthPackagesRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'local_geographic_region_set_id' => 'string',
        'page_number' => 'int',
        'page_size' => 'int',
        'peer_geographic_region_set_id' => 'string',
        'project_name' => 'string',
        'tag_filters' => '\Volcengine\Transitrouter\Model\TagFilterForDescribeTransitRouterBandwidthPackagesInput[]',
        'transit_router_bandwidth_package_ids' => 'string[]',
        'transit_router_bandwidth_package_name' => 'string',
        'transit_router_peer_attachment_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'local_geographic_region_set_id' => null,
        'page_number' => 'int32',
        'page_size' => 'int32',
        'peer_geographic_region_set_id' => null,
        'project_name' => null,
        'tag_filters' => null,
        'transit_router_bandwidth_package_ids' => null,
        'transit_router_bandwidth_package_name' => null,
        'transit_router_peer_attachment_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'local_geographic_region_set_id' => 'LocalGeographicRegionSetId',
        'page_number' => 'PageNumber',
        'page_size' => 'PageSize',
        'peer_geographic_region_set_id' => 'PeerGeographicRegionSetId',
        'project_name' => 'ProjectName',
        'tag_filters' => 'TagFilters',
        'transit_router_bandwidth_package_ids' => 'TransitRouterBandwidthPackageIds',
        'transit_router_bandwidth_package_name' => 'TransitRouterBandwidthPackageName',
        'transit_router_peer_attachment_id' => 'TransitRouterPeerAttachmentId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'local_geographic_region_set_id' => 'setLocalGeographicRegionSetId',
        'page_number' => 'setPageNumber',
        'page_size' => 'setPageSize',
        'peer_geographic_region_set_id' => 'setPeerGeographicRegionSetId',
        'project_name' => 'setProjectName',
        'tag_filters' => 'setTagFilters',
        'transit_router_bandwidth_package_ids' => 'setTransitRouterBandwidthPackageIds',
        'transit_router_bandwidth_package_name' => 'setTransitRouterBandwidthPackageName',
        'transit_router_peer_attachment_id' => 'setTransitRouterPeerAttachmentId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'local_geographic_region_set_id' => 'getLocalGeographicRegionSetId',
        'page_number' => 'getPageNumber',
        'page_size' => 'getPageSize',
        'peer_geographic_region_set_id' => 'getPeerGeographicRegionSetId',
        'project_name' => 'getProjectName',
        'tag_filters' => 'getTagFilters',
        'transit_router_bandwidth_package_ids' => 'getTransitRouterBandwidthPackageIds',
        'transit_router_bandwidth_package_name' => 'getTransitRouterBandwidthPackageName',
        'transit_router_peer_attachment_id' => 'getTransitRouterPeerAttachmentId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['local_geographic_region_set_id'] = isset($data['local_geographic_region_set_id']) ? $data['local_geographic_region_set_id'] : null;
        $this->container['page_number'] = isset($data['page_number']) ? $data['page_number'] : null;
        $this->container['page_size'] = isset($data['page_size']) ? $data['page_size'] : null;
        $this->container['peer_geographic_region_set_id'] = isset($data['peer_geographic_region_set_id']) ? $data['peer_geographic_region_set_id'] : null;
        $this->container['project_name'] = isset($data['project_name']) ? $data['project_name'] : null;
        $this->container['tag_filters'] = isset($data['tag_filters']) ? $data['tag_filters'] : null;
        $this->container['transit_router_bandwidth_package_ids'] = isset($data['transit_router_bandwidth_package_ids']) ? $data['transit_router_bandwidth_package_ids'] : null;
        $this->container['transit_router_bandwidth_package_name'] = isset($data['transit_router_bandwidth_package_name']) ? $data['transit_router_bandwidth_package_name'] : null;
        $this->container['transit_router_peer_attachment_id'] = isset($data['transit_router_peer_attachment_id']) ? $data['transit_router_peer_attachment_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets local_geographic_region_set_id
     *
     * @return string
     */
    public function getLocalGeographicRegionSetId()
    {
        return $this->container['local_geographic_region_set_id'];
    }

    /**
     * Sets local_geographic_region_set_id
     *
     * @param string $local_geographic_region_set_id local_geographic_region_set_id
     *
     * @return $this
     */
    public function setLocalGeographicRegionSetId($local_geographic_region_set_id)
    {
        $this->container['local_geographic_region_set_id'] = $local_geographic_region_set_id;

        return $this;
    }

    /**
     * Gets page_number
     *
     * @return int
     */
    public function getPageNumber()
    {
        return $this->container['page_number'];
    }

    /**
     * Sets page_number
     *
     * @param int $page_number page_number
     *
     * @return $this
     */
    public function setPageNumber($page_number)
    {
        $this->container['page_number'] = $page_number;

        return $this;
    }

    /**
     * Gets page_size
     *
     * @return int
     */
    public function getPageSize()
    {
        return $this->container['page_size'];
    }

    /**
     * Sets page_size
     *
     * @param int $page_size page_size
     *
     * @return $this
     */
    public function setPageSize($page_size)
    {
        $this->container['page_size'] = $page_size;

        return $this;
    }

    /**
     * Gets peer_geographic_region_set_id
     *
     * @return string
     */
    public function getPeerGeographicRegionSetId()
    {
        return $this->container['peer_geographic_region_set_id'];
    }

    /**
     * Sets peer_geographic_region_set_id
     *
     * @param string $peer_geographic_region_set_id peer_geographic_region_set_id
     *
     * @return $this
     */
    public function setPeerGeographicRegionSetId($peer_geographic_region_set_id)
    {
        $this->container['peer_geographic_region_set_id'] = $peer_geographic_region_set_id;

        return $this;
    }

    /**
     * Gets project_name
     *
     * @return string
     */
    public function getProjectName()
    {
        return $this->container['project_name'];
    }

    /**
     * Sets project_name
     *
     * @param string $project_name project_name
     *
     * @return $this
     */
    public function setProjectName($project_name)
    {
        $this->container['project_name'] = $project_name;

        return $this;
    }

    /**
     * Gets tag_filters
     *
     * @return \Volcengine\Transitrouter\Model\TagFilterForDescribeTransitRouterBandwidthPackagesInput[]
     */
    public function getTagFilters()
    {
        return $this->container['tag_filters'];
    }

    /**
     * Sets tag_filters
     *
     * @param \Volcengine\Transitrouter\Model\TagFilterForDescribeTransitRouterBandwidthPackagesInput[] $tag_filters tag_filters
     *
     * @return $this
     */
    public function setTagFilters($tag_filters)
    {
        $this->container['tag_filters'] = $tag_filters;

        return $this;
    }

    /**
     * Gets transit_router_bandwidth_package_ids
     *
     * @return string[]
     */
    public function getTransitRouterBandwidthPackageIds()
    {
        return $this->container['transit_router_bandwidth_package_ids'];
    }

    /**
     * Sets transit_router_bandwidth_package_ids
     *
     * @param string[] $transit_router_bandwidth_package_ids transit_router_bandwidth_package_ids
     *
     * @return $this
     */
    public function setTransitRouterBandwidthPackageIds($transit_router_bandwidth_package_ids)
    {
        $this->container['transit_router_bandwidth_package_ids'] = $transit_router_bandwidth_package_ids;

        return $this;
    }

    /**
     * Gets transit_router_bandwidth_package_name
     *
     * @return string
     */
    public function getTransitRouterBandwidthPackageName()
    {
        return $this->container['transit_router_bandwidth_package_name'];
    }

    /**
     * Sets transit_router_bandwidth_package_name
     *
     * @param string $transit_router_bandwidth_package_name transit_router_bandwidth_package_name
     *
     * @return $this
     */
    public function setTransitRouterBandwidthPackageName($transit_router_bandwidth_package_name)
    {
        $this->container['transit_router_bandwidth_package_name'] = $transit_router_bandwidth_package_name;

        return $this;
    }

    /**
     * Gets transit_router_peer_attachment_id
     *
     * @return string
     */
    public function getTransitRouterPeerAttachmentId()
    {
        return $this->container['transit_router_peer_attachment_id'];
    }

    /**
     * Sets transit_router_peer_attachment_id
     *
     * @param string $transit_router_peer_attachment_id transit_router_peer_attachment_id
     *
     * @return $this
     */
    public function setTransitRouterPeerAttachmentId($transit_router_peer_attachment_id)
    {
        $this->container['transit_router_peer_attachment_id'] = $transit_router_peer_attachment_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

